#!/usr/bin/env bash
#
# Build a Fedora package (dist/guake-<version>-<release>.noarch.rpm) for this
# fork with rpmbuild.
#
# Usage:
#   scripts/build-rpm.sh [VERSION]            # on Fedora, with rpm-build installed
#   scripts/build-rpm.sh --docker [VERSION]   # anywhere with Docker (uses fedora:latest)
#
# VERSION is chosen like in build-deb.sh (tag, or <BASE_VERSION>+fork.<date>.<sha>).
# RPM versions cannot contain "-", so "3.10.1-fork.1" becomes Version 3.10.1,
# Release fork.1.
#
# The python package goes to /usr/share/guake/python instead of Fedora's
# versioned site-packages, and /usr/bin/guake adds that folder to sys.path.
# That way one noarch .rpm installs on every current Fedora release, whatever
# its python3 minor version.
#
# Environment overrides:
#   BASE_VERSION    upstream version the fork is based on (default 3.10.1)
#   RPM_EPOCH       Epoch (default 1, so Fedora's own guake never replaces the fork)
#   FEDORA_IMAGE    image used by --docker (default fedora:latest)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
BASE_VERSION="${BASE_VERSION:-3.10.1}"
PYTHON="${PYTHON:-/usr/bin/python3}"
RPM_EPOCH="${RPM_EPOCH:-1}"
FEDORA_IMAGE="${FEDORA_IMAGE:-fedora:latest}"
PY_DEST="usr/share/guake/python"
BUILD_DEPS="rpm-build make gettext glib2 git findutils python3 python3-pip \
python3-setuptools python3-setuptools_scm python3-wheel python3-packaging"

log() { printf '\033[1;34m[build-rpm]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[build-rpm] error:\033[0m %s\n' "$*" >&2; exit 1; }

if [ "${1:-}" = "--docker" ]; then
    shift
    command -v docker >/dev/null 2>&1 || die "--docker needs Docker"
    VERSION_ARG="${1:-}"
    log "Building inside $FEDORA_IMAGE"
    # shellcheck disable=SC2016
    docker run --rm -v "$ROOT_DIR:/src" -e BASE_VERSION -e RPM_EPOCH "$FEDORA_IMAGE" bash -c '
        set -e
        dnf install -y -q '"$BUILD_DEPS"' >/dev/null
        git config --global --add safe.directory /src
        /src/scripts/build-rpm.sh "$1"
        chown -R "$2" /src/dist
    ' _ "$VERSION_ARG" "$(id -u):$(id -g)"
    exit 0
fi

for tool in rpmbuild make msgfmt glib-compile-schemas git "$PYTHON"; do
    command -v "$tool" >/dev/null 2>&1 \
        || die "'$tool' is required (on Fedora: sudo dnf install $BUILD_DEPS), or use --docker"
done

# shellcheck source=scripts/lib/stage-guake.sh
. "$ROOT_DIR/scripts/lib/stage-guake.sh"

VERSION="${1:-$(derive_version)}"
VERSION="${VERSION#v}"
[[ "$VERSION" =~ ^[0-9][A-Za-z0-9.+~-]*$ ]] || die "'$VERSION' is not a valid version"
RPM_VERSION="${VERSION%%-*}"
RPM_RELEASE="1"
if [ "$RPM_VERSION" != "$VERSION" ]; then
    RPM_RELEASE="${VERSION#*-}"
    RPM_RELEASE="${RPM_RELEASE//-/.}"
fi
PY_VERSION="$(pep440_version "$VERSION")"
log "RPM version: $RPM_EPOCH:$RPM_VERSION-$RPM_RELEASE (python version: $PY_VERSION)"

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/guake-rpm.XXXXXX")"
trap 'rm -rf "$WORK_DIR"' EXIT
SRC_DIR="$WORK_DIR/src"
STAGE_DIR="$WORK_DIR/stage"
mkdir -p "$STAGE_DIR"
snapshot_source "$SRC_DIR"
stage_guake "$SRC_DIR" "$STAGE_DIR" "$PY_DEST" "$PY_VERSION" rpm

# --------------------------------------------------------------------------
# Launchers that find the private python folder
# --------------------------------------------------------------------------
write_launcher() {
    cat >"$STAGE_DIR/usr/bin/$1" <<EOF
#!/usr/bin/python3
import sys

sys.path.insert(0, "/$PY_DEST")
from $2 import $3  # noqa: E402

sys.exit($3())
EOF
}
write_launcher guake guake.main exec_main
write_launcher guake-toggle guake.guake_toggle toggle_guake_by_dbus
install -Dm644 "$SRC_DIR/COPYING" "$STAGE_DIR/usr/share/licenses/guake/COPYING"

find "$STAGE_DIR" -type d -exec chmod 0755 {} +
find "$STAGE_DIR" -type f -exec chmod 0644 {} +
chmod 0755 "$STAGE_DIR"/usr/bin/*

# --------------------------------------------------------------------------
# File list and spec
# --------------------------------------------------------------------------
FILE_LIST="$WORK_DIR/files.list"
{
    # Directories the package owns; /usr/share/locale/* and friends belong
    # to the filesystem package.
    (cd "$STAGE_DIR" && find usr/share/guake -type d) | sed 's|^|%dir /|'
    (cd "$STAGE_DIR" && find . -type f -o -type l) | sed 's|^\.||' \
        | grep -v '^/usr/share/licenses/' | sed 's|.*|"&"|'
    echo '%license /usr/share/licenses/guake/COPYING'
} >"$FILE_LIST"

SPEC="$WORK_DIR/guake.spec"
cat >"$SPEC" <<EOF
# Generated by scripts/build-rpm.sh from an already staged tree.
%global debug_package %{nil}
%global __brp_python_bytecompile %{nil}
%global __brp_mangle_shebangs %{nil}

Name:           guake
Epoch:          $RPM_EPOCH
Version:        $RPM_VERSION
Release:        $RPM_RELEASE
Summary:        Drop-down terminal for GNOME (dazller4554328 fork)
License:        GPL-2.0-or-later
URL:            https://github.com/dazller4554328/guake
BuildArch:      noarch
AutoReqProv:    no
Provides:       guake = %{epoch}:%{version}-%{release}

Requires:       python3 >= 3.8
Requires:       python3-gobject
Requires:       python3-cairo
Requires:       python3-dbus
Requires:       python3-pyyaml
Requires:       gtk3
Requires:       vte291
Requires:       keybinder3
Requires:       libwnck3
Requires:       libnotify
Requires:       libutempter
Requires:       glib2
Requires:       dconf
Recommends:     openssh-clients
Recommends:     sshpass
Recommends:     libsecret
Recommends:     python3-cryptography
Suggests:       libayatana-appindicator-gtk3

%description
Guake is a top-down "Quake style" terminal for GNOME: press a hotkey and a
terminal slides down from the top of the screen.

This fork adds a saved SSH servers manager (passwords kept in the desktop
keyring and passed through sshpass, coloured server tabs, encrypted backup
and restore) and a Tabby-style SFTP panel for uploading and downloading
files next to a terminal tab.

%install
cp -a "$STAGE_DIR"/. %{buildroot}/

%post
glib-compile-schemas /usr/share/glib-2.0/schemas >/dev/null 2>&1 || :

%postun
glib-compile-schemas /usr/share/glib-2.0/schemas >/dev/null 2>&1 || :

%files -f $FILE_LIST
EOF

log "Building the rpm"
rpmbuild -bb "$SPEC" \
    --define "_topdir $WORK_DIR/rpmbuild" \
    --define "_rpmdir $WORK_DIR/rpms" \
    --define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" \
    >"$WORK_DIR/rpmbuild.log" 2>&1 || { tail -30 "$WORK_DIR/rpmbuild.log" >&2; die "rpmbuild failed"; }

mkdir -p "$DIST_DIR"
RPM_FILE="$(find "$WORK_DIR/rpms" -name '*.rpm' -print -quit)"
cp "$RPM_FILE" "$DIST_DIR/"
log "Done: $DIST_DIR/$(basename "$RPM_FILE")"
